# frp 服务器端配置 - 小龙 Control Tower v3
# 生成时间: Fri Mar 20 08:50:42 CST 2026

[common]
bind_port = 7000
token = fBibhbQKy38XQT4YcClFbjuSGt1zrBsw

# 仪表盘
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = 2vH6jaU82LNn5Nu8

log_file = ./frps.log
log_level = info
log_max_days = 30

heartbeat_timeout = 90
max_pool_count = 50
tcp_mux = true
